In [5]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [7]:
df.shape

(569, 33)

In [8]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [9]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train test split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)
# df.iloc[:, 1:] => : means "all rows", 1: means "columns from position 1 to the end" (everything except the first column). This returns a DataFrame.
# df.iloc[:, 0] => : means "all rows", 0 means "column at position 0" (the first column). This returns a Series — the first column's values.

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""
These lines standardize the features (mean = 0, std = 1), which most ML models (including neural nets) train better with.
scaler = StandardScaler() → creates a scaler object from scikit-learn that will learn how to transform data: z = (x - mean) / std.

X_train = scaler.fit_transform(X_train) → does two things at once:
fit: computes the mean and standard deviation of each column using only the training data.
transform: applies (x - mean) / std to X_train using those computed values, replacing it with the standardized version.

X_test = scaler.transform(X_test) → applies the same mean/std learned from the training set to the test set — it does not re-fit. 
This is important: the test set must be scaled using training statistics, 
otherwise you'd leak information from the test set into your preprocessing (data leakage), and it also wouldn't reflect how the model would behave on truly unseen data in production.

So the rule of thumb: fit_transform on train, transform (only) on test/validation/new data.
"""

"\nThese lines standardize the features (mean = 0, std = 1), which most ML models (including neural nets) train better with.\nscaler = StandardScaler() → creates a scaler object from scikit-learn that will learn how to transform data: z = (x - mean) / std.\n\nX_train = scaler.fit_transform(X_train) → does two things at once:\nfit: computes the mean and standard deviation of each column using only the training data.\ntransform: applies (x - mean) / std to X_train using those computed values, replacing it with the standardized version.\n\nX_test = scaler.transform(X_test) → applies the same mean/std learned from the training set to the test set — it does not re-fit. \nThis is important: the test set must be scaled using training statistics, \notherwise you'd leak information from the test set into your preprocessing (data leakage), and it also wouldn't reflect how the model would behave on truly unseen data in production.\n\nSo the rule of thumb: fit_transform on train, transform (only) on test/validation/new data.\n"

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

"""
Same logic as the StandardScaler. fit_transform makes the labeling of y train and transform the labels inplace
transform on test set uses the labeling done by fit on the train data and transform the test set accordingly.
"""

'\nSame logic as the StandardScaler. fit_transform makes the labeling of y train and transform the labels inplace\ntransform on test set uses the labeling done by fit on the train data and transform the test set accordingly.\n'

In [13]:
y_train

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0])

Numpy arrays to Pytorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

Defining The Model

In [ ]:
class MySimpleNN(): ## only a simple and single neuron
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
        
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        epsilon = 1e-7 # to prevent log(0)
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred)).mean()
        # .mean() reduces the per-sample losses into a single scalar by averaging the loss across all samples in the batch. 
        # This is what turns "how wrong was each individual prediction" into "how wrong is the model overall, on average, for this batch.
        return loss

In [ ]:
learning_rate = 0.1 # the alpha - size of the steps the optimizer takes when updating the NN's weights to minimize errors
epochs = 25 # each epoch is one complete pass of the entire training dataset through the neural network. 
#Because a network cannnot find all underlying patterns in a single pass, it requires multiple epochs to analyze and refine its weights

Training Pipeline

In [41]:
# create model
model = MySimpleNN(X_train_tensor)

# training model in a loop
for epoch in range(epochs):    
    # forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    # print(f"Epoch: {epoch}, loss: {loss}")

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad(): # the adjusting should not be tracked by gradient tracking
        model.weights -= learning_rate * model.weights.grad # actual formula: w_new = w_prev - alpha * (dw/dl)
        model.bias -= learning_rate * model.bias.grad # actual formula: b_new = b_prev - alpha * (db/dl)
        
    # zero gradients - as it will accumulate the existing gradients, we must make it zero before going to the next iteration
    # remember: we are not making the weights and bias into zero, only resetting the gradient as 0 before moving forward
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    # print loss in each epoch
    print(f"Loss: {loss.item()}, Epoch: {epoch + 1}")

Loss: 4.180487705673456, Epoch: 1
Loss: 4.096347002096261, Epoch: 2
Loss: 4.0096997113758865, Epoch: 3

In [42]:
print(f"Weights: {model.weights}")
print(f"Bias: {model.bias}")

Weights: tensor([[ 0.0871],
        [ 0.2914],
        [ 0.6021],
        [ 0.7196],
        [ 0.9297],
        [ 0.2360],
        [ 0.7121],
        [ 0.3143],
        [ 0.5731],
        [ 0.6111],
        [ 0.8872],
        [ 0.8368],
        [ 0.5968],
        [ 0.9267],
        [ 0.2606],
        [ 0.4157],
        [ 0.9410],
        [ 0.7770],
        [ 0.9034],
        [ 0.2862],
        [-0.0271],
        [ 0.9410],
        [ 0.8651],
        [ 0.9223],
        [ 0.1769],
        [ 0.8687],
        [ 0.4063],
        [ 0.4127],
        [ 0.8627],
        [ 0.5790]], dtype=torch.float64, requires_grad=True)
Bias: tensor([0.0088], dtype=torch.float64, requires_grad=True)

In [46]:
# model evaluation with new weight and bias value
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")
    
print(y_pred)

Accuracy: 0.5030778646469116
tensor([[0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

**Future Improvements**
1. NN Module for automatic weight and bias initialization for complex networks
2. Using loss functions available in PyTorch
3. No manual gradient descent, should use PyTorch optim classes.